name: deploy-docker-manylinux2014_x86_64_cuda_11.7

on:
    push:
        branches:
            - main
    release:
        types: 
            - published

jobs:
    build-manylinux_x86_64_cuda_11_7:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push manylinux2014_x86_64_cuda-11.7
              id: docker_build
              uses: docker/build-push-action@v3
              with:
                  push: true
                  file: ./docker/manylinux2014_x86_64_cuda_11.7/Dockerfile
                  tags: sameli/manylinux2014_x86_64_cuda_11.7:latest

            - name: Image digest
              run: echo ${{ steps.docker_build.outputs.digest }}

    # test-cuda-11-7:
    #     runs-on: ubuntu-latest
    #     steps:
    #         - name: Install Snap
    #           run: |
    #             sudo apt update
    #             sudo apt install snapd
    #
    #         - name: Install Docker
    #           run: |
    #             sudo snap install docker
    #             sudo groupadd -f docker
    #             sudo usermod -aG docker $USER
    #             newgrp docker
    #
    #         - name: Pull Docker Image
    #           run: docker pull sameli/manylinux2014_x86_64_cuda_11.7
    #
    #         - name: Run Docker Image
    #           run: docker run -t sameli/manylinux2014_x86_64_cuda_11.7 nvcc --version
